### ISSUE TITLE
Atom will not build against iojs 3.2.0+ / node 4

### ISSUE THREAD

**Issue by ryanpcmcquen** [atom/atom#8508]
I have commented on the node-runas issue which I believe to be the cause of this, but perhaps it should be a new issue (and will get more exposure here):

```
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.17
gyp ERR! command "/usr/bin/iojs" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/SBo/atom-1.0.7/build/node_modules/runas
gyp ERR! node -v v3.2.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.10.17
npm ERR! argv "/usr/bin/iojs" "/usr/bin/npm" "--userconfig=/tmp/SBo/atom-1.0.7/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v3.2.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/SBo/atom-1.0.7/build/npm-debug.log
```

Here is the full npm-debug.log: https://gist.github.com/ryanpcmcquen/8e798b2d172b96c5d9ab

And the node-runas issue:

https://github.com/atom/node-runas/issues/11

**Comment by 50Wliu** [comment]
Atom currently can't be built using io.js v3.x since that would require all NAN dependencies to be upgraded to 2.x.

**Comment by 50Wliu** [comment]
Re-opening as a tracking issue.

**Comment by ryanpcmcquen** [comment]
@50Wliu what version is it supposed to build with? I am having issues here on node 0.12.6, 0.12.7 and iojs 2.5.0.

**Comment by 50Wliu** [comment]
Node 0.12 and iojs 2.x should both be fine...could you try running `script/clean` before `script/build`?

**Comment by ryanpcmcquen** [comment]
1.0.8 builds with node 0.12.7, so that works for me! :+1:

**Comment by ryanpcmcquen** [comment]
It must have been an issue with me not running `script/clean`, because I was able to build 1.0.7 also after doing that. Thank you @50Wliu!

**Comment by 50Wliu** [comment]
No longer blocked - all native modules that Atom depends on have been updated to support Node 4.

**Comment by ryanpcmcquen** [comment]
@50Wliu will not build for me with Node 4.1.1: https://gist.github.com/ryanpcmcquen/adf295a1bfc9646be3cf

Or should I be building master?

**Comment by YuriSolovyov** [comment]
Is that 4.x or 4.0 ?

**Comment by conraid** [comment]
Idem for me. With master branch. 
Node: v4.1.1
npm: v2.14.4
Installing build modules...
In file included from ../src/main.cc:1:0:
../node_modules/nan/nan.h:260:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:255:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:660:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:660:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:664:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:664:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:671:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:671:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/main.cc:1:
/root/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/root/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/main.cc:1:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:675:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:682:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/runas/src/main.o] Errore 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib64/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.1-cf
gyp ERR! command "/usr/bin/node" "/usr/lib64/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/pkg/atom-master/build/node_modules/runas
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.2.1-cf
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/tmp/pkg/atom-master/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/pkg/atom-master/build/npm-debug.log


Error also cz-electron-32 branch

**Comment by YuriSolovyov** [comment]
could be related: https://github.com/atom/node-runas/issues/11

**Comment by 50Wliu** [comment]
@zcbenz I think `build/package.json` also needs to be updated: https://github.com/atom/atom/blob/4e4b3cef373797227d102baa57d2d5af47064ec4/build/package.json#L36

**Comment by conraid** [comment]
@50Wliu yes, now building without error. Thanks.

**Comment by ryanpcmcquen** [comment]
Built here (Node: v4.1.1, npm: v2.14.4, Linux: 4.1.8) after changing the `build/package.json` file. :+1:

**Comment by ryanpcmcquen** [comment]
Here is one-liner for packagers until the new release:

```
## fix package dependency (upstream will merge this on the next release)
sed -i.bak 's/"runas": "^2",/"runas": "^3",/g' build/package.json
```

**Comment by mnquintana** [comment]
Fixed in https://github.com/atom/atom/pull/8945
