### ISSUE TITLE
Atom fails to build on 64-bit FreeBSD 10.3; node-gyp and python2 issues

### ISSUE THREAD

**Issue by fusion809** [atom/atom#11890]
Hi,

I followed the [freebsd.md build guide](https://github.com/atom/atom/blob/master/docs/build-instructions/freebsd.md) and installed a few extra deps I thought may be missing, namely I ran:

``` bash
sudo pkg install node npm libgnome-keyring gcc make python2
sudo npm install -g node-gyp
sudo npm config set python /usr/local/bin/python2 -g
```

then I got the source code of Atom 1.7.4 and cd'ed into it, via running:

``` bash
curl -OL https://github.com/atom/atom/archive/v1.7.4.tar.gz
tar -xzf v1.7.4.tar.gz
cd atom-1.7.4
```

Finally I ran:

``` bash
script/build
```

and received the output:

``` bash
Node: v5.11.1
npm: v2.13.3
Installing build modules...
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):
gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack AttributeError: 'module' object has no attribute 'python_version'
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:202:12)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:484:12)
gyp ERR! System FreeBSD 10.3-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/home/fusion809/atom-1.7.4/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/fusion809/atom-1.7.4/build/node_modules/runas
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/bin/python2 -c import platform; print(platform.python_version());
gyp ERR! stack Traceback (most recent call last):
gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack AttributeError: 'module' object has no attribute 'python_version'
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:202:12)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:484:12)
gyp ERR! System FreeBSD 10.3-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/home/fusion809/atom-1.7.4/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/fusion809/atom-1.7.4/build/node_modules/minidump
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! FreeBSD 10.3-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/home/fusion809/atom-1.7.4/build/node_modules/.bin/npm" "--userconfig=/usr/home/fusion809/atom-1.7.4/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.11.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/fusion809/atom-1.7.4/build/npm-debug.log
```

npm-debug.log can be found [here](http://paste2.org/tfDc67tg). I have noticed some other Python issues, like I tried to upload my build log to paste2.org using `pastebinit` but it gave the error:

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/pastebinit", line 27, in <module>
    from ConfigParser import SafeConfigParser
  File "/usr/local/lib/python2.7/ConfigParser.py", line 91, in <module>
    from collections import OrderedDict as _default_dict
  File "/usr/local/lib/python2.7/collections.py", line 4, in <module>
    from _abcoll import *
  File "/usr/local/lib/python2.7/_abcoll.py", line 70, in <module>
    Iterable.register(str)
  File "/usr/local/lib/python2.7/abc.py", line 107, in register
    if not isinstance(subclass, (type, types.ClassType)):
AttributeError: 'module' object has no attribute 'ClassType'
```

so I am guessing that I am missing some Python2 package?

Thanks for your time,
Brenton

**Comment by SonOfFlyingPig** [comment]
I am getting similar errors on 11.0-RELEASE

**Comment by SonOfFlyingPig** [comment]
Console output + debug log:

[error.txt](https://github.com/atom/atom/files/565612/error.txt)
[npm-debug.log.txt](https://github.com/atom/atom/files/565614/npm-debug.log.txt)
