### ISSUE TITLE
Atom 1.47.0 (and Beta 1.48.0) break Markdown Preview Plus (preview remains empty)

### ISSUE THREAD

**Issue by jamiejenkins** [atom/atom#20754]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Markdown Preview Plus preview doesn't work after installing 1.47.0 (or 1.48.0 beta).

### Steps to Reproduce

1. Update to 1.47.0
2. Open markdown file
3. Open preview window

**Expected behavior:**

html preview based on markdown appears

**Actual behavior:**

tab appears but is completely blank

**Reproduces how often:**

100% always blank

### Versions

apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.16
git 2.24.2

markdown-preview-plus 3.11.5 (issue https://github.com/atom-community/markdown-preview-plus/issues/487)

### Additional Information

This stopped working on both Windows 10 and macOS Catalina versions of Atom

**Comment by darangi** [comment]
Can you provide a sample of the markdown file used in this scenario? I currently can' t reproduce this both on `1.47.0` and `1.48-beta`

**Comment by jamiejenkins** [comment]
It is blank even with a very simple markdown file like below.  I have tried disabling all other packages as well.  

```markdown
**BOLD**

-----

- First
- Second
```

**Comment by lierdakil** [comment]
Some technical info: Electron 5 disables webview tags by default, and Atom doesn't enable those. MPP relies on webview for preview isolation. Unless this is fixed upstream, MPP is basically dead in the water, since I don't currently have the time for a complete re-write.

**Comment by lierdakil** [comment]
Ah, this is actually a duplicate of #20604. And there's already a PR: #20741

**Comment by lierdakil** [comment]
And upstream just ignored that, apparently. Well, that's discouraging.

**Comment by Arcanemagus** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/20604. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by jamiejenkins** [comment]
Looks like the fix #20741 for #20604 was just merged to master an hour ago. Thanks.

**Comment by ashthespy** [comment]
But it didn't make the merge window for 1.47.0 right?

**Comment by jamiejenkins** [comment]
No - as 1.47.0 was already released earlier.  I do not know which version the fix will be in.

**Comment by lierdakil** [comment]
@ashthespy 1.47.0 is out already, so no. Unless upstream backports this as 1.47.1, we'll have to wait for 1.48.0

**Comment by staplegun** [comment]
Markdown preview still broken in 1.48 Windows - gives `Previewing Markdown Failed - r.trim is not a function`

**Comment by lierdakil** [comment]
@staplegun markdown-preview-plus is confirmed by multiple people to work on Atom 1.48.0, so this is a different issue. Please report it on the relevant repository and include the test Markdown file the issue reproduces on and configuration used. Thanks.

**Comment by ianbytchek** [comment]
Reported at https://github.com/atom-community/markdown-preview-plus/issues/500.
