### ISSUE TITLE
EISDIR: illegal operation on a [particular] directory

### ISSUE THREAD

**Issue by jiku** [atom/atom#6814]
While attempting to open a folder, I got the error below. After renaming, it opened just fine. Making a new, empty folder with the same name yielded the same error.

I'm on OS X 10.10.4 using 0.199.0. The path is still read- and usable to other processes, and just before manually installing 0.199.0, I had the folder open and working fine with 0.194.0.

Rebooting didn't help, so I'll look for references to the path in Atom's config files and on my system.

```
index.js:62 Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:596:19)
    at Object.fs.readFileSync (fs.js:428:28)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at File.module.exports.File.readSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:248:36)
    at TextBuffer.module.exports.TextBuffer.updateCachedDiskContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:940:85)
    at TextBuffer.module.exports.TextBuffer.loadSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:969:12)
    at Project.module.exports.Project.buildBufferSync (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:431:14)
    at Project.module.exports.Project.bufferForPathSync (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:407:61)
    at TokenizedBuffer.module.exports.TokenizedBuffer.deserializeParams (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:82:36)index.js:62 handleSetupError
```

**Comment by jiku** [comment]
Ok, deleting ```editor*``` files referencing the path in ```~/.atom/storage/``` fixed it. Must've been unsaved changes, an unclean exit or some such.

**Comment by erikbrannstrom** [comment]
FYI, I had the exact same problem and @jiku's solution worked for me as well. I'm on OS X 10.10.3 and I could reproduce the issue in at least 0.198 and 0.199 (it used to work, but can't say which version).
