### PR TITLE
Support building with node 0.12.x and io.js 1.x

### LINKED ISSUE #3184: Error when building latest version on OSX
I could build it without issue on my MBA that run OSX 10.10 but it fails on an iMac with OSX 10.9.4 + XCode up to date.
Here's the log of the `script/build` task: 

```
Node: v0.11.13
npm: v1.4.9
Installing build modules...
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"v0.11.13","npm":"1.4.9"})
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"v0.11.13","npm":"1.4.9"})
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"v0.11.13","npm":"1.4.9"})
Installing apm...
npm WARN package.json github-url-from-git@1.1.1 No repository field.
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/cedric/github/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/cedric/github/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/Users/cedric/github/atom/apm/node_modules/atom-package-manager/bin/apm: line 40: 69330 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

I also tried to build it on node 0.10 but when running `npm install` I get: 

```
../src/scrollbar-style-observer-mac.mm:42:3: error: no matching function for call to
      'uv_async_init'
  uv_async_init(loop, &async, asyncSendHandler);
  ^~~~~~~~~~~~~
/Users/cedric/.node-gyp/0.10.21/deps/uv/include/uv.h:1186:15: note: candidate function not
      viable: no known conversion from 'void (uv_async_t *)' to 'uv_async_cb' (aka
      'void (*)(uv_async_t *, int)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
              ^
1 error generated.
make: *** [Release/obj.target/scrollbar-style-observer/src/scrollbar-style-observer-mac.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cedric/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/Users/cedric/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cedric/github/atom/node_modules/scrollbar-style
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
```
And then forcing a build after that gave the same error as with node v0.11.13.

Is there's something I missed regarding my system configuration.

### LINKED ISSUE #5493: Not building on Mac OS X 10.10.2 with io.js
Hi there!

I'm trying to build on `Mac OS X 10.10.2` from the `0.177.0` tag using `io.js v1.2.0` but I get the following output:

```
~/g/atom git:tags/v0.177.0 ❯❯❯ script/clean
~/g/atom git:tags/v0.177.0 ❯❯❯ nvm use iojs
Now using io.js v1.2.0
~/g/atom git:tags/v0.177.0 ❯❯❯ script/build
Node: v1.2.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:622:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:617:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:1993:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:1994:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:1995:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:1995:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1996:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/murphy/.nvm/versions/io.js/v1.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:85:13)
gyp ERR! stack     at ChildProcess.emit (events.js:153:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/murphy/.nvm/versions/io.js/v1.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/murphy/github/atom/build/node_modules/runas
gyp ERR! node -v v1.2.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/murphy/.nvm/versions/io.js/v1.2.0/bin/iojs" "/Users/murphy/.nvm/versions/io.js/v1.2.0/bin/npm" "--userconfig=/Users/murphy/github/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! node v1.2.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/murphy/github/atom/build/npm-debug.log
~/g/atom git:tags/v0.177.0 ❯❯❯  
```

I've got the X-Code command line tools installed. Trying to build with `node 0.10.36` makes it almost all of the way through the build, but gives a different error when deduping modules.

Almost the same issue as https://github.com/atom/apm/issues/195, but removing the node_modules folder didn't help me at all.

EDIT: running `script/clean` before building with `node 0.10.36` did result in a successful build, however.

Thanks!

### LINKED ISSUE #5591: Allow building with node 12
Since node 12 came out a week ago, [people have been trying to build with it](https://github.com/atom/atom/issues/5587) and they have been having issues.

```
[connexo@archgott atom]$ script/build 
Node: v0.12.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

cc @franktopel

### PR DESCRIPTION
**Pull request by kevinsawicki**
Make Atom buildable with node 0.12.x and io.js 1.x

Closes #3184
Closes #5493
Closes #5591

### CODE REVIEW

**Comment by lee-dohm** [comment]
:clap: Woot!

**Comment by kevinsawicki** [comment]
If people are still seeing issues, try removing the `apm/node_modules` folder from the Atom source tree since it may have a bad version cached. Then just `script/bootstrap` or `script/build` after deleting it.

**Comment by paulcbetts** [comment]
:clap::clap::clap:
