### ISSUE TITLE
Not building on Mac OS X 10.10.2 with io.js

### ISSUE THREAD

**Issue by murphyrandle** [atom/atom#5493]
Hi there!

I'm trying to build on `Mac OS X 10.10.2` from the `0.177.0` tag using `io.js v1.2.0` but I get the following output:

```
~/g/atom git:tags/v0.177.0 ❯❯❯ script/clean
~/g/atom git:tags/v0.177.0 ❯❯❯ nvm use iojs
Now using io.js v1.2.0
~/g/atom git:tags/v0.177.0 ❯❯❯ script/build
Node: v1.2.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:622:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:617:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:1993:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:1994:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:1995:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/murphy/.node-gyp/1.2.0/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/main.cc:1:
../node_modules/nan/nan.h:1995:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1996:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/murphy/.nvm/versions/io.js/v1.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:85:13)
gyp ERR! stack     at ChildProcess.emit (events.js:153:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/murphy/.nvm/versions/io.js/v1.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/murphy/github/atom/build/node_modules/runas
gyp ERR! node -v v1.2.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/murphy/.nvm/versions/io.js/v1.2.0/bin/iojs" "/Users/murphy/.nvm/versions/io.js/v1.2.0/bin/npm" "--userconfig=/Users/murphy/github/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! node v1.2.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/murphy/github/atom/build/npm-debug.log
~/g/atom git:tags/v0.177.0 ❯❯❯  
```

I've got the X-Code command line tools installed. Trying to build with `node 0.10.36` makes it almost all of the way through the build, but gives a different error when deduping modules.

Almost the same issue as https://github.com/atom/apm/issues/195, but removing the node_modules folder didn't help me at all.

EDIT: running `script/clean` before building with `node 0.10.36` did result in a successful build, however.

Thanks!

**Comment by izuzak** [comment]
I'm seeing the same, not really sure why. That's looks like the same error which is thrown when a dependency is not using the latest version of `nan`. 

cc @kevinsawicki @zcbenz

**Comment by kevinsawicki** [comment]
I believe this is related to the node version you are using to build Atom, can you try node `0.10.x`?

**Comment by lee-dohm** [comment]
I reproduced both the break on iojs and the successful build (after clean) on node v0.10.x.

**Comment by kevinsawicki** [comment]
I upgraded the build dependency on runas to version 2.0

**Comment by kevinsawicki** [comment]
@lee-dohm can you pull from master and try again with io.js and see if you get the same error?

**Comment by izuzak** [comment]
@kevinsawicki Still breaks with io.js, but a bit later in the process:

```
$ script/build
Node: v1.2.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
In file included from ../src/onig-reg-exp.cc:1:
../node_modules/nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/onig-reg-exp.cc:1:
../node_modules/nan/nan.h:622:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:617:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:1993:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/onig-reg-exp.cc:1:
../node_modules/nan/nan.h:1994:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/onig-reg-exp.cc:1:
../node_modules/nan/nan.h:1995:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/onig-reg-exp.cc:1:
../node_modules/nan/nan.h:1995:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1996:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/onig_scanner/src/onig-reg-exp.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/izuzak/github/atom/build/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:85:13)
gyp ERR! stack     at ChildProcess.emit (events.js:153:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/izuzak/github/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/izuzak/github/atom/apm/node_modules/atom-package-manager/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v1.2.0
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
child_process: customFds option is deprecated, use stdio instead.
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
../node_modules/nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
../node_modules/nan/nan.h:622:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:617:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:1993:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
../node_modules/nan/nan.h:1994:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
../node_modules/nan/nan.h:1995:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean 'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/izuzak/.node-gyp/1.2.0/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../src/repository.cc:22:
In file included from ../src/repository.h:29:
../node_modules/nan/nan.h:1995:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1996:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
7 errors generated.
make: *** [Release/obj.target/git/src/repository.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/izuzak/github/atom/build/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:85:13)
gyp ERR! stack     at ChildProcess.emit (events.js:153:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/izuzak/github/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/izuzak/github/atom/apm/node_modules/atom-package-manager/node_modules/git-utils
gyp ERR! node -v v1.2.0
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! oniguruma@3.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@3.0.6 install script.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/Users/izuzak/github/atom/build/node_modules/.bin/npm" "--userconfig=/Users/izuzak/github/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /Users/izuzak/github/atom/apm
npm ERR! node -v v1.2.0
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by lee-dohm** [comment]
@kevinsawicki Confirmed. Same as @izuzak.

**Comment by kevinsawicki** [comment]
Okay, I think this should be fixed now that apm has been upgraded.

```
$ script/bootstrap
Node: v1.2.0
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
```

**Comment by izuzak** [comment]
Not sure if this is something specific to my setup, but I'm now getting this (building from f1bd4b2):

```
$ script/clean

$ script/build
Node: v1.2.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/izuzak/github/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/izuzak/github/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/Users/izuzak/github/atom/apm/node_modules/atom-package-manager/bin/apm: line 40: 53066 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

@lee-dohm what's on your :computer: ? :)

**Comment by lee-dohm** [comment]
Building on iojs v1.2.0 using 9765435389af0b635db43101c42b0596a062bfdf, I get the same as @izuzak. (Sorry, had to show up at my day job for a while :laughing:)

**Comment by lee-dohm** [comment]
Looking deeper at the error message ... didn't I see that you merged something about removing the harmony collections, @kevinsawicki?

**Comment by kevinsawicki** [comment]
>  didn't I see that you merged something about removing the harmony collections, @kevinsawicki?

There was a PR opened today on apm about harmony-collections but it wasn't merged yet.

**Comment by lee-dohm** [comment]
Ah ok, that must be what I was thinking of.

**Comment by geoff-codes** [comment]
@izuzak The latest issue you mentioned is the same one @totallymike reported way back when [here](https://github.com/atom/atom/issues/3184#issuecomment-52131341). I'd wager most of the rest of these issues boil down to the same issue.

To clarify: As @kevinsawicki hinted above,  you **cannot** presently build with io.js or node 0.12.0 (or 0.11.x), because the API/ABI of these versions are incompatible with the `node` that apm uses. Presently, the build script simply grabs the binary dist of [v0.10.35, which is hardcoded in the script](https://github.com/atom/apm/blob/master/script/download-node.js#L107). The modules built and installed _prior_ to this step in the build process are built against _your_ node, and after v0.10.35 is installed, it inherits those modules.

Need proof? Download node v0.10.35 and io.js or 0.12.0.

`nm node | grep _node_module_register`
With 0.10.35: nada.
The others: `00000001005c2f77 T _node_module_register`.

There's a few different ways to handle this. What I proposed with [apm #293](https://github.com/atom/apm/pull/293) was to bump the node installed with apm to 0.12.0, since this is the quickest "fix", and probably the direction you'd want to be heading in. Unfortunately, after doing this, the build completes, but the app is non-functional (see the nslog issue above).

The other reliable way to work around this would be to have a pre-bootstrap script that downloads and installs a local copy of v0.10.35, prepending its location to the PATH, and ensure it doesn't pick up any stray node modules already installed elsewhere — before any invocations of node (including the bootstrap and build scripts). This way, you ensure the API/headers will match both before and after apm is installed, and all loadable modules will be built against the proper symbols in the node binary.

But, that's a total pain in the ass. :hankey: 

Hopefully, that all makes sense. Thoughts?

**Comment by paulcbetts** [comment]
I don't think this will work even if you do fix that - all of the native node modules currently built in Atom Shell have a custom Magic™ version of rvagg/nan, that I suspect doesn't recognize current versions of io.js. 

The good news is that I believe I read that this situation is temporary - in Chrome >= 41, V8 versions will be synced up with io.js again, and everything will Return To Sanity™, and packages can use the latest public nan, not need a special one-off version.

**Comment by izuzak** [comment]
Thanks for the explanations @geoff-codes and @paulcbetts. :bow: I'm not sure I understand all the details, but I'm sure it's helpful for resolving this issue. Also, since the [build docs](https://github.com/atom/atom/blob/master/docs/build-instructions/os-x.md#requirements) list node 0.10.x as a requirement and Atom builds just fine with that -- I wouldn't consider this a priority (but I think it's worth keeping the issue open).

**Comment by geoff-codes** [comment]
@izuzak Actually, [those requirements](https://github.com/atom/atom/blob/master/docs/build-instructions/os-x.md#requirements) tripped me up a bit.

Myself, not being an everyday node.js user, didn't realize that "- node.js v0.10.x"  excludes _newer_ versions.

That is, in most cases, when I see a requirement like "ruby 1.9.3", I say to myself, "ok, so ruby 2.x should be fine", and I applied that same logic here.

IMHO, I think it might be worth updating the docs to mention this, since 0.10.x is no longer the latest "stable" release branch, maybe something like:

```markdown
- node.js v0.10.x (**not** 0.11.x, 0.12.x, or io.js) 
```
...  while this specific requirement is in place.

**Comment by izuzak** [comment]
@geoff-codes Thanks for pointing that out -- I see what you're saying and I wouldn't be :-1: on adding more text to the docs if this is causing confusion. However, I'd rather not list all the possible configurations that don't work and would rather say something like "yes, we officially support exactly this version".

I'm sure you'll agree that users who want to build Atom themselves are aware that they're driving off the main road, and an implicit requirement for doing that is that you follow the build instructions. If the build is failing -- go back and see if you followed the instructions exactly. Adding explanations like that to every step of the build process is something I wouldn't be :+1: on. 

For building yourself, I think we should document build requirements which are officially supported. If some configuration is not listed as officially supported (e.g. io.js build) -- then you're on your own (it might work, but we provide no guarantees). Documenting that something does not work adds the same kind of responsibility of making sure that the docs are truthful over time and also adds the overhead of deciding what goes into the list of things that do not work. For example, you need to make sure the docs are updated when it becomes possible to build Atom with io.js (also, needs to have a list of versions), and when a new version of node is released 0.13.x which we don't support either, or when a new fork of node.js similar to io.js is released, or if building with io.js stops working at some version. Adding something to the docs right now is easy, making sure that the docs reflect reality over time is not easy. Just my :thought_balloon:.

**Comment by geoff-codes** [comment]
Myself, I wasn't speaking about io.js, just lazy folk like me who don't pay attention to version numbers.
Honestly, what it really boils to on Mac OS X:

  * ~~[~~node.js~~](http://nodejs.org/download)~~ [**v0.10.x**](http://nodejs.org/dist/v0.10.36/) —  _**NOT**_ the version of [node](http://nodejs.org/dist/v0.10.36/) you installed with [:beer: brew] (https://github.com/Homebrew/homebrew).

Which really should quite adequately close #3184 and this issue.

**Comment by kevinsawicki** [comment]
io.js and node 0.12 should now be supported via #5628, please comment if you see any issues once you pull that commit.
