### PR TITLE
Fix potential null reference callback invokation in script/clean

### LINKED ISSUE #11328: script/clean fails with error
On OS X, with Node 5.8.0 and atom at dea5c5560e7a98977cf1d265f55686c1efc1d04b, running `./script/clean` does not succeed:

```
[atom (master):zap:]> ./script/clean 
/Users/daniel/atom/atom/script/utils/child-process-wrapper.js:21
     callback(null);
     ^

TypeError: callback is not a function
   at /Users/daniel/atom/atom/script/utils/child-process-wrapper.js:21:7
   at ChildProcess.exithandler (child_process.js:193:7)
   at emitTwo (events.js:100:13)
   at ChildProcess.emit (events.js:185:7)
   at maybeClose (internal/child_process.js:850:16)
   at Socket.<anonymous> (internal/child_process.js:323:11)
   at emitOne (events.js:90:13)
   at Socket.emit (events.js:182:7)
   at Pipe._onclose (net.js:475:12)
```

This appears to be a regression introduced by https://github.com/atom/atom/commit/76f9f43e6aec3d53b1b23b893648eac238090a60 - cc @nathansobo  @damieng 

Thanks to @abe33 and @thomasjo for helping investigate / confirm.

### PR DESCRIPTION
**Pull request by thomasjo**
A bug was introduced in https://github.com/atom/atom/commit/76f9f43e6aec3d53b1b23b893648eac238090a60, which boiled down to not checking whether the (seemingly) optional callback in `ChildProcess.safeExec` is defined before invokation.

I wasn't sure whether we wanted to add a condition on the `else` statement, or set `callback` to a noop function. I opted for the formed, but I'm open to suggestions.

/cc @thedaniel @abe33 @damieng 

---

Fixes #11328

### CODE REVIEW

**Comment by damieng** [comment]
Looks good to me, thanks for spotting this.
