### PR TITLE
Use apm@1.12.2 with Node v4 and npm v3 \o/

### LINKED ISSUE #5109: Path too long exception on Windows install
I download AtomSetup.exe
I run it as an administrator
I agree there are probably curious permission setups and my user directory is mapped to a central server.
I get no choices where to install from the installer.
Other applications have worked
I get the error dialog. Here's the log. 
I can't alter where it tries to install, nor am I clear why the install path is too long.
Chocolatey didn't  install 174.1 either - there's clearly something pathological in my setup.
Any chance of being able to configure where it installs to and from? 
============SquirrelSetup.log============
Program: Starting Squirrel Updater: --install .
Program: Starting install, writing to C:\Users\john.drummond\AppData\Local\SquirrelTemp
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\john.drummond\AppData\Local\atom\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Reading RELEASES file from C:\Users\john.drummond\AppData\Local\SquirrelTemp
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
ApplyReleasesImpl: Writing files to app directory: C:\Users\john.drummond\AppData\Local\atom\app-0.174.0
IEnableLogger: Failed to write file: C:\Users\john.drummond\AppData\Local\atom\app-0.174.0: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8b.<copyFileToLocation>b__8a()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.PhysicalPackageFile.GetStream()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8b.<copyFileToLocation>b__8a()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.UpdateManager.ApplyReleasesImpl.copyFileToLocation(FileSystemInfo target, IPackageFile x)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass84.<installPackageToAppDir>b__80(IPackageFile x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass84.<installPackageToAppDir>b__7f()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<installPackageToAppDir>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__4b`1.MoveNext()

### PR DESCRIPTION
**Pull request by BinaryMuse**
```
                  __              __ __
                 /\ \            /\ \\ \
  ___     ___    \_\ \     __    \ \ \\ \
/' _ `\  / __`\  /'_` \  /'__`\   \ \ \\ \_
/\ \/\ \/\ \L\ \/\ \L\ \/\  __/    \ \__ ,__\
\ \_\ \_\ \____/\ \___,_\ \____\    \/_/\_\_/
 \/_/\/_/\/___/  \/__,_ /\/____/       \/_/


                                    __
                                  /'__`\
     ___   _____     ___ ___     /\_\L\ \
   /' _ `\/\ '__`\ /' __` __`\   \/_/_\_<_
   /\ \/\ \ \ \L\ \/\ \/\ \/\ \    /\ \L\ \
   \ \_\ \_\ \ ,__/\ \_\ \_\ \_\   \ \____/
    \/_/\/_/\ \ \/  \/_/\/_/\/_/    \/___/
             \ \_\
              \/_/
```

This bumps apm to 1.11.1, which includes atom/apm#562 and atom/apm#563. Since npm 3 flattens packages by default, the build had to change relatively significantly, and I'm sure there are more edge cases to track down. This also bumps Atom's own npm to 3.9.5.

Of particular note, I removed the `apm clean` command that runs as part of the build. It didn't seem to be working in the first place, and seems to have trouble with npm 3's package flattening; maybe we can delegate to `npm prune` here. Since published builds get built from scratch, I think this is probably not a huge deal.

@atom/core, @atom/feedback, @damieng, I would love for you to pull down this branch and try to build Atom and make sure it runs correctly and that package-related operations work. It's _extremely likely_ you will have to run `script/clean` first; sorry, things are just too different.

Fixes #5109
Makes #7822 (more) possible
Probably a bunch of others too

### CODE REVIEW

**Comment by BinaryMuse** [comment]
As a side note, this is the first time this build is being run on GitHub's internal CI server, which has [given us issues](https://github.com/atom/apm/pull/457#issuecomment-202176819) with this type of upgrade in the past — so I will probably spend a significant amount of energy (and possibly time) getting that working.

**Comment by 50Wliu** [comment]
> [`apm clean`] didn't seem to be working in the first place

In my experience it's worked, as it properly removed `release-notes` when that got cut from Atom.  `npm prune` looks like it'll have problems with everything listed in `packageDependencies` as those are _already_ marked as extraneous when running `npm ls`.  If that can be fixed though...:+1: for using prune instead.

**Comment by Ben3eeE** [comment]
I get a build error when trying to build this branch on Windows 10. I can build master without error.
[cmd log.txt](https://github.com/atom/atom/files/298841/cmd.log.txt)
[npm-debug.txt](https://github.com/atom/atom/files/298840/npm-debug.txt)

**Comment by thomasjo** [comment]
@Ben3eeE Did you run `script/clean` prior to `script/build`?

**Comment by thomasjo** [comment]
Been running this for a few hours on OS X 10.11, and haven't noticed any regressions yet.

**Comment by 50Wliu** [comment]
Ok, I get the same errors as @Ben3eeE while attempting to build on a brand-new laptop (so no Atom previously installed).

**Comment by 50Wliu** [comment]
Perhaps [this line](https://github.com/atom/apm/blob/b25e8fee56a94e9a884307e87139e1322ca0d755/bin/npm.cmd#L5) should be `set maybe_node_gyp_path=%~dp0\..\node_modules\.bin\node-gyp.cmd` instead?

**Comment by Ben3eeE** [comment]
Yes I did script/clean before. Full list of commands I ran are in cmd log i uploaded. Included all from switching branch to error.

**Comment by 50Wliu** [comment]
Solved it:
1. Change `apm.cmd` to
```cmd
@echo off
setlocal

if exist "%~dp0\node.exe" (
  "%~dp0\node.exe" "%~dp0/../lib/cli.js" %*
) else (
  node.exe "%~dp0/../lib/cli.js" %*
)
```
2. cd into `apm\node_modules\atom-package-manager\node_modules\npm\node-gyp-bin` and change the path `node-gyp.cmd` looks for to `%~dp0\..\..\..\node-gyp\bin\node-gyp.js`.

Obviously this is a hacky solution, but setting `npm_config_node_gyp` doesn't work as described above.  I'll continue investigating until I find something that works properly.

**Comment by 50Wliu** [comment]
So after fixing the node-gyp issues and finishing the build process I ended up facing #10819 :frowning:.

I also tried building on an Ubuntu 16.04 64-bit VM but got the same error as in https://travis-ci.org/atom/atom/jobs/135187713 which seems to be related to x64 compatibility.

**Comment by gjtorikian** [comment]
> So after fixing the node-gyp issues and finishing the build process I ended up facing #10819

I'm hitting the same issue in the ARM builds issue (https://github.com/atom/atom/issues/7822). I finally tracked the problem down to https://github.com/nodegit/nodegit/pull/1026. In short, `nodegit@0.13.0` is broken and 0.13.1 has the fix. The submodule checker is broken in 0.13.0.

NodeGit needs to publish their newest release: https://github.com/nodegit/nodegit/issues/1044#issuecomment-223843351

**Comment by 50Wliu** [comment]
Ok, managed to fix the node-gyp issue with atom/apm#571.  Now it's failing when trying to install Nodegit 0.13.1.  Apparently it can't find `node-pre-gyp.cmd`, but I checked and the file exists...:confused:.

Retrying seems to have fixed it, but I'm not sure if it just skipped pre-gyp because it assumed that Nodegit installed properly, if it was a one-time thing, or if something else went wrong.  I'll try again tomorrow.

Unfortunately now I'm stuck at a `Error: Cannot find module '../build/Release/pathwatcher.node'` error when starting Atom.  Not sure if that's related to Nodegit.

**Comment by damieng** [comment]
The build servers are showing this error;

```
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
```

**Comment by nonnymoose** [comment]
This fixed bug #10742 for me!

**Comment by as-cii** [comment]
I think the spec failures we're seeing here (for Janky) will be resolved with #11998.

**Comment by 50Wliu** [comment]
Shouldn't https://github.com/atom/atom/blob/e5a3c9ebe0391c22d71194d5a3c164fa87c6fd12/script/bootstrap#L78 be targeting 4.4.5?

**Comment by thomasjo** [comment]
> Shouldn't https://github.com/atom/atom/blob/e5a3c9ebe0391c22d71194d5a3c164fa87c6fd12/script/bootstrap#L78 be targeting 4.4.5?

Good catch ⚾️

**Comment by thomasjo** [comment]
Can we 🚢 a new version of apm to include https://github.com/atom/apm/pull/591? Not crucial to get that into this PR I suppose, but we'll need it soon-ish anyway to pave the way for the next LTS release of Node.js (Oct 2016).

If nothing else, it will help reduce the graceful-fs deprecation "spam" we're currently forced to live with.

**Comment by as-cii** [comment]
> Can we 🚢 a new version of apm to include atom/apm#591? Not crucial to get that into this PR I suppose, but we'll need it soon-ish anyway to pave the way for the next LTS release of Node.js (Oct 2016).

I think we're going to release a new version as part of atom/apm#592 (which is essential in order for this pull-request to get merged), so we will include atom/apm#591 too in that release. Thanks for the heads-up, @thomasjo! 🙇

**Comment by as-cii** [comment]
Aside from Travis timing out (which we're going to solve by switching to CircleCI, #12207), I think this is ready to 🚢. `atom-win` is failing, but based on @damieng's work, we should be able to use AppVeyor as a drop-in replacement: in the meantime, we're actively working to fix atom-win too on Janky.

@nathansobo @BinaryMuse: what do you think? 👀 💭

**Comment by nathansobo** [comment]
Unfortunately, we've found a problem where apm is unable to require files out of Atom's ASAR bundle. This wasn't an issue for *building* Atom since apm uses an unpacked resource path in that case, but it is an issue for installing packages with a built version of Atom. Going to roll this back, fix the issue, and try again. 😢

**Comment by elprans** [comment]
@nathansobo You may want to take alook at this PR: https://github.com/electron/asar-require/pull/2  May be related.

**Comment by maxbrunsfeld** [comment]
❤️  Thanks for the heads up @elprans.
