### ISSUE TITLE
Atom 1.0.5 crashing on startup

### ISSUE THREAD

**Issue by Reisz** [atom/atom#8272]
Ever since I updated to 1.0.4 on win8 x64 the app would crash, before it even rendered. I continued to use 1.0.3, which broke when I updated to 1.0.5 hoping that would work again. I have since upgraded to win10. Here is the error log, when i call `atom -t`:
```
[8928:0807/201638:ERROR:crash_reporter_win.cc(70)] Cannot initialize out-of-process crash handler
[8928:0807/201639:INFO:CONSOLE(0)] Application server failed { [Error: listen EADDRINUSE \\.\pipe\atom-sock]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '\\\\.\\pipe\\atom-sock',
  port: -1 }
[8740:0807/201639:INFO:renderer_main.cc(212)] Renderer process started
[8928:0807/201639:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[8928:0807/201639:ERROR:cache_util.cc(132)] Unable to move cache folder C:\Users\Daniel\AppData\Roaming\Atom\GPU
 C:\Users\Daniel\AppData\Roaming\Atom\old_GPUCache_000
[8928:0807/201639:ERROR:cache_creator.cc(133)] Unable to create cache
[8928:0807/201639:ERROR:shader_disk_cache.cc(614)] Shader Cache Creation failed: -2
warning: removing Breakpad handler out of order
[8928:0807/201644:INFO:CONSOLE(27)] "Error: Cannot find module 'temp'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\src\modul
js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Daniel\.atom\packages\pigments\spec\color-project-spec.coffee:3:8)
  at Object.<anonymous> (C:\Users\Daniel\.atom\packages\pigments\spec\color-project-spec.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\co
h\lib\coffee-cash.js:85:19)
  at Module.load (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\coffee-script\lib
script\register.js:45:36)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at requireSpecs (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\spec-suite.js:21:7)
  at runAllSpecs (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\spec-suite.js:78:7)
  at Object.<anonymous> (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\spec-suite.js:87:5
  at Object.<anonymous> (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\spec-suite.js:90:4
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\src\babel.js:163:
  at Module.load (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\coffee-script\lib
script\register.js:45:36)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at module.exports.runSpecSuite (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\jasmine-h
:61:5)
  at Object.<anonymous> (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\spec-bootstrap.js:
  at Object.<anonymous> (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\spec-bootstrap.js:
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\src\babel.js:163:
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/Daniel/AppData/Local/atom/app-1.0.5/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/Daniel/AppData/Local/atom/app-1.0.5/resources/app.asar/static/index.js:36:7
", source: C:\Users\Daniel\AppData\Local\atom\app-1.0.5\resources\app.asar\spec\spec-bootstrap.js (27)
```

**Comment by Reisz** [comment]
Forgot to mention that I already tried reinstalling and this message is from a fresh install.

**Comment by Nosenation** [comment]
I have similar problem on OS X. Just upgraded to 1.0.5 and i see this error (no other pane is visible except devtools and console).

```
Error
    at new Parser (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/node_modules/less/lib/less/parser.js:333:27)
    at LessCache.module.exports.LessCache.parseLess (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:244:16)
    at LessCache.module.exports.LessCache.cssForFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:275:20)
    at LessCache.module.exports.LessCache.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/less-cache/lib/less-cache.js:263:19)
    at LessCompileCache.module.exports.LessCompileCache.read (/Applications/Atom.app/Contents/Resources/app.asar/src/less-compile-cache.js:36:25)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:310:33)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:286:21)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:203:24)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:266:12)
    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/theme-manager.js:261:19)
```
at:
```
file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js line: 66
```

**Comment by mnquintana** [comment]
@Nosenation That looks like a different problem - would you mind opening a new issue?

**Comment by Nosenation** [comment]
@mnquintana Np.

**Comment by damieng** [comment]
Is this still an issue with newer builds for you?

**Comment by Nosenation** [comment]
@damieng Nope. Now everything works fine.

**Comment by damieng** [comment]
Great :)
