### ISSUE TITLE
Attempting new build on 16.04.1 LTS - install failure

### ISSUE THREAD

**Issue by jslovato** [atom/atom#12419]
Following the instructions for Linux/Ubuntu from:
https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

I can not install atom.

ansible@ip-172-31-17-83:~/atom$ sudo script/grunt install
Loading "compile-packages-slug-task.coffee" tasks...ERROR
>> Error: Cannot find module 'season'
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache'
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache/package.json'

Running "install" task
Warning: Cannot read property 'description' of undefined Use --force to continue.

Aborted due to warnings.

Execution Time (2016-08-14 17:02:40 UTC)
loading tasks  2.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 2.8s
 
Using --force produces this:

~/atom$ sudo script/grunt install --force
Loading "compile-packages-slug-task.coffee" tasks...ERROR
>> Error: Cannot find module 'season'
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache'
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache/package.json'

Running "install" task
Warning: Cannot read property 'description' of undefined Used --force, continuing.

Done, but with warnings.

Execution Time (2016-08-14 17:08:48 UTC)
loading tasks  2.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 2.8s

~/atom$ nvm --version
0.31.4
~/atom$ node --version
v4.4.7

I did pull latest branch from github prior to attempting install. Everything else worked fine until this step.

Thanks.

**Comment by Nikki1993** [comment]
Did you install build-essentials prior building? I think the command was `sudo apt install build-essentials`

**Comment by 50Wliu** [comment]
I would do what @Nikki1993 suggested; that is try running `script/clean` and then building again.  From the console output it looks like some npm packages weren't installed.

**Comment by jslovato** [comment]
I did install all the prereqs as required, it is part of the documentation as I've noted to having read.

:~/atom$ sudo dpkg-query -l 'build-essential*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version       Architecture  Description
+++-================-=============-=============-=====================================
ii  build-essential  12.1ubuntu2   amd64         Informational list of build-essential
:~/atom$ sudo dpkg-query -l 'libgnome-keyring-dev*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version       Architecture  Description
+++-================-=============-=============-=====================================
ii  libgnome-keyring 3.12.0-1build amd64         Development files for GNOME keyring s
:~/atom$ sudo dpkg-query -l 'fakeroot*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version       Architecture  Description
+++-================-=============-=============-=====================================
ii  fakeroot         1.20.2-1ubunt amd64         tool for simulating superuser privile

Ran script/clean and made another build attempt with no change in result:

ansible@ip-172-31-17-83:~/atom$ sudo script/clean
ansible@ip-172-31-17-83:~/atom$ script/build
Node: v4.4.7
npm: v3.10.6
Installing build modules...


ansible@ip-172-31-17-83:~/atom$ sudo script/grunt install
Loading "compile-packages-slug-task.coffee" tasks...ERROR
>> Error: Cannot find module 'season'
Loading "prebuild-less-task.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache'
Loading "Gruntfile.coffee" tasks...ERROR
>> Error: Cannot find module 'less-cache/package.json'

Running "install" task
Warning: Cannot read property 'description' of undefined Use --force to continue.

Aborted due to warnings.


Execution Time (2016-08-16 01:20:55 UTC)
loading tasks  4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 4s

**Comment by Nikki1993** [comment]
That's odd. Could you upgrade your NodeJS to 6.3.1 version? 
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

do script/clean and redo the build?

**Comment by jslovato** [comment]
Thank you! That worked much better.

:~$ nvm install 6.3.1
Downloading https://nodejs.org/dist/v6.3.1/node-v6.3.1-linux-x64.tar.xz...
######################################################################## 100.0%
Now using node v6.3.1 (npm v3.10.3)
:~$ cd atom/
:~/atom$ script/clean
:~/atom$ script/build
Node: v6.3.1
npm: v3.10.3
Installing build modules...
=> Took 138501ms.

Installing apm...
=> Took 153143ms.

Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.52.0 ✓
Installing atom-light-syntax@0.28.0 ✓
Installing atom-light-ui@0.44.0 ✓
Installing base16-tomorrow-dark-theme@1.1.0 ✓
Installing base16-tomorrow-light-theme@1.1.1 ✓
Installing one-dark-ui@1.5.0 ✓
Installing one-light-ui@1.5.0 ✓
Installing one-dark-syntax@1.3.0 ✓
Installing one-light-syntax@1.3.0 ✓
Installing solarized-dark-syntax@1.0.2 ✓
Installing solarized-light-syntax@1.0.2 ✓
Installing about@1.5.3 ✓
Installing archive-view@0.61.1 ✓
Installing autocomplete-atom-api@0.10.0 ✓
Installing autocomplete-css@0.11.2 ✓
Installing autocomplete-html@0.7.2 ✓
Installing autocomplete-plus@2.31.1 ✓
Installing autocomplete-snippets@1.11.0 ✓
Installing autoflow@0.27.0 ✓
Installing autosave@0.23.1 ✓
Installing background-tips@0.26.1 ✓
Installing bookmarks@0.41.0 ✓
Installing bracket-matcher@0.82.1 ✓
Installing command-palette@0.38.0 ✓
Installing deprecation-cop@0.54.1 ✓
Installing dev-live-reload@0.47.0 ✓
Installing encoding-selector@0.22.0 ✓
Installing exception-reporting@0.39.0 ✓
Installing find-and-replace@0.201.0 ✓
Installing fuzzy-finder@1.3.0 ✓
Installing git-diff@1.1.0 ✓
Installing go-to-line@0.31.0 ✓
Installing grammar-selector@0.48.1 ✓
Installing image-view@0.58.2 ✓
Installing incompatible-packages@0.26.1 ✓
Installing keybinding-resolver@0.35.0 ✓
Installing line-ending-selector@0.5.0 ✓
Installing link@0.31.1 ✓
Installing markdown-preview@0.158.0 ✓
Installing metrics@0.53.1 ✓
Installing notifications@0.65.0 ✓
Installing open-on-github@1.2.0 ✓
Installing package-generator@1.0.0 ✓
Installing settings-view@0.241.2 ✓
Installing snippets@1.0.2 ✓
Installing spell-check@0.67.1 ✓
Installing status-bar@1.4.1 ✓
Installing styleguide@0.47.0 ✓
Installing symbols-view@0.113.0 ✓
Installing tabs@0.100.2 ✓
Installing timecop@0.33.2 ✓
Installing tree-view@0.208.2 ✓
Installing update-package-dependencies@0.10.0 ✓
Installing welcome@0.34.0 ✓
Installing whitespace@0.33.0 ✓
Installing wrap-guide@0.38.1 ✓
Installing language-c@0.52.1 ✓
Installing language-clojure@0.21.0 ✓
Installing language-coffee-script@0.47.2 ✓
Installing language-csharp@0.12.1 ✓
Installing language-css@0.37.1 ✓
Installing language-gfm@0.88.0 ✓
Installing language-git@0.15.0 ✓
Installing language-go@0.42.1 ✓
Installing language-html@0.45.1 ✓
Installing language-hyperlink@0.16.0 ✓
Installing language-java@0.23.0 ✓
Installing language-javascript@0.119.0 ✓
Installing language-json@0.18.2 ✓
Installing language-less@0.29.5 ✓
Installing language-make@0.22.2 ✓
Installing language-mustache@0.13.0 ✓
Installing language-objective-c@0.15.1 ✓
Installing language-perl@0.35.0 ✓
Installing language-php@0.37.2 ✓
Installing language-property-list@0.8.0 ✓
Installing language-python@0.45.0 ✓
Installing language-ruby@0.69.0 ✓
Installing language-ruby-on-rails@0.25.0 ✓
Installing language-sass@0.56.0 ✓
Installing language-shellscript@0.22.4 ✓
Installing language-source@0.9.0 ✓
Installing language-sql@0.23.0 ✓
Installing language-text@0.7.1 ✓
Installing language-todo@0.28.0 ✓
Installing language-toml@0.18.0 ✓
Installing language-xml@0.34.9 ✓
Installing language-yaml@0.26.0 ✓
=> Took 533096ms.

Deduping modules ✓
=> Took 3302ms.

Running "download-electron" task


Running "download-electron-chromedriver" task


Running "build" task

Running "babel:dist" (babel) task

Running "coffee:glob_to_multiple" (coffee) task
>> 341 files created.

Running "prebuild-less:src" (prebuild-less) task
>> 1610 files compiled, 0 files reused

Running "cson:glob_to_multiple" (cson) task
>> 172 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task
Generating parser from "node_modules/snippets/lib/snippet-body.pegjs"...
Parser "/home/ansible/atom/out/Atom Beta/resources/app/node_modules/snippets/lib/snippet-body.js" generated in 39ms.

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "set-version" task

Running "generate-asar" task

Done, without errors.


Execution Time (2016-08-16 19:56:55 UTC)
loading tasks                       4.1s  ▇ 2%
download-electron               2m 58.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 68%
download-electron-chromedriver      4.1s  ▇ 2%
build                              18.5s  ▇▇▇ 7%
coffee:glob_to_multiple            10.5s  ▇▇ 4%
prebuild-less:src                    29s  ▇▇▇▇ 11%
cson:glob_to_multiple               3.7s  ▇ 1%
generate-asar                      10.2s  ▇▇ 4%
Total 4m 22.9s


:~/atom$ sudo script/grunt install
(node:24700) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Running "install" task

Done, without errors.


Execution Time (2016-08-16 20:02:01 UTC)
loading tasks  2.3s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 31%
install        5.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 69%
Total 7.6s

**Comment by 50Wliu** [comment]
Glad to hear it @jslovato :).  I'm not sure why Node LTS doesn't work - I'm also running 4.4.7 and that builds fine for me.

**Comment by andyrichardson** [comment]
Is there a reason this issue is still open?

**Comment by jslovato** [comment]
no sir. Just forgot to close it. :)
