### ISSUE TITLE
Atom throwing several "Failed to load the xyz package" errors

### ISSUE THREAD

**Issue by daftpanda** [atom/atom#8891]
Hi guys,

First of all, I'd like to say that I'm new to github and want to apologize before if I do/post/whatever in a wrong way here...

Yesterday I launched my atom.exe like I always do but was prompted with several errors like in the title:

    Failed to load the emmet package...

See below for an example:
![image](https://cloud.githubusercontent.com/assets/14540591/10018322/0d067ca6-6136-11e5-99bc-fa86f4b2ae60.png)

I assume it's because of the new update to atom itself? Any ideas how to fix this?
**I already tried to uninstall and reinstall all the packages - no help.**
**And I completely removed atom from my system and reinstalled it again - no help.**

**Atom version:**
1.0.15

**System:**
Windows 7 Ultimate 64bit

Best regards,
daftpanda

**Comment by abe33** [comment]
For the record here's a couple of issues where it was initially reported:

atom-minimap/minimap#299
abe33/atom-pigments#42
olmokramer/atom-tree-view-git-branch#3

**Comment by daftpanda** [comment]
Here are some attempts to fix it which didn't help:

* <code>apm rebuild</code>
* <code>apm rebuild-module-cache</code>
* tried removing the <code>node_modules</code> directory in the package and run <code>apm install</code> manually in it
* Completely close all instances of Atom --> Delete the directory <code>~/.atom/compile-cache</code> --> Start Atom again

**Comment by saviilsy** [comment]
Same here, clean install with only atom-typescript installed and it won't work due to "Cannot find module" errors - author suggested it might be core atom related. 

I started to look into it, and I don't know if this is related, but I noticed that those modules that throw error (for example line 'require("ntypescript")') do not contain index.js file, only "main" property in package.js. If I add that index.js with module.export = [file that main property points to], that module starts to work and the error moves to another module with the same problem.

I quit adding those index.js's as every dependancy inside module needs it and it's a big job to fix manually - unfornately though atom is useless now since nothing works :(

**Comment by LoicGrobol** [comment]
Also https://github.com/Hackafe/atom-sync-settings/issues/128

**Comment by Evpok** [comment]
Also

**Comment by Pyraah** [comment]
Same issue here after upgrading from 1.0.13 to 1.0.15. Clean install cannot solve this problem.

![capture](http://puu.sh/kkBx7.png)

**Comment by saviilsy** [comment]
The last working version seems to be 1.0.11. If You rollback to it, packages seem to find dependancies, seems like updating io.js is the culprit(?).

HOWEVER there are loads of other errors with this. Using 1.0.11 modules cannot automatically install external module dependencies, it always fails and keeps hanging the editor when trying to use it. If you install them via apm by name it works, but if You issue a more general "apm install", it fails horribly.

Seems Atom is quite broken... At least on Windows.

**Comment by kevinsawicki** [comment]
Can people try removing the following directories, reinstalling the packages that are showing errors, and see if they still see this issue?

* `~/.atom/.apm`
* `~/.atom/.npm`
* `~/.atom/.node-gyp`

These are just cache directories used to store modules and libraries, not actual packages.

@nathansobo pointed out there was a recent npm server issue causing empty tarballs.

From http://status.npmjs.org:

```
Empty tarballs responses
Resolved - Cache invalidation is complete. 
Sep 16, 16:29 UTC
Monitoring - Cache invalidation is ongoing and should be complete within 15 minutes. 
Sep 16, 15:55 UTC
Identified - A bug in code we rolled out to our canary server at 10:52 UTC today, and which our automated checks haven't caught caused us to return empty tarball responses to some of our users. We rolled the deployment back at 14:29 UTC and are working on invalidating caches affected by this outage. 
Sep 16, 15:25 UTC
```

**Comment by Evpok** [comment]
It still happened after a full cleanup of everything atom-related on my PC,
the whole .atom folder included.

**Comment by kevinsawicki** [comment]
@Evpok and what packages are currently failing for you? sync-settings only? or others?

**Comment by Evpok** [comment]
I actually didn't try reinstalling them all, I gave up and switch to my
Linux boot when I saw I could even install this one. I'll give minimap and
pigments a shot tomorrow, those were among those that failed before the
cleanup.

**Comment by Pyraah** [comment]
Works fine with 1.0.11, thanks @saviilsy.

**Comment by daftpanda** [comment]
@kevinsawicki I deleted the directories you mentioned (didn't get the <code>.npm</code> though), restarted, deleted the failing packages, installed them again:

same problem...

**Comment by daftpanda** [comment]
Checked for updates, then this occurred:

**Comment by daftpanda** [comment]
checked for updates, then this occurred:

![image](https://cloud.githubusercontent.com/assets/14540591/10072575/0fb8d5e6-62c3-11e5-9c29-78580f0d87e5.png)

probably relating to the topic (issue)

**Comment by netmou** [comment]
i  have the same issue on updating from  v1.011 to v1.0.15, win10x64
but v10.16 is very normal

**Comment by daftpanda** [comment]
Completely removed atom from my system (again...),
clean installed it via the AtomSetup.exe downloaded from atom.io...
installed my packages - problem persists :(

**Comment by kevinsawicki** [comment]
Atom `1.0.17` is now available on https://github.com/atom/atom/releases/tag/v1.0.17

Can everyone give that version a try and see if this issue persists?

There was an Windows issue fixed in that version where file handles were leaking and causing `ENOENT` errors to surface. That could be potentially what was causing these `require` issues since the files couldn't be read correctly and so the libraries failed to load.

**Comment by guziks** [comment]
For me the issue still persists with `1.0.17`

**Comment by kevinsawicki** [comment]
@guziks can you share a screenshot of the error(s)? Thanks.

**Comment by guziks** [comment]
This is what I get from minimap package:

![minimap-error](https://cloud.githubusercontent.com/assets/7124125/10084957/b9f44478-630e-11e5-93a5-1a39b76a2e27.png)

**Comment by kevinsawicki** [comment]
@guziks and does a non-empty `~/.atom/packages/minimap/node_modules/atom-utils` folder exist?

**Comment by guziks** [comment]
Yes, it exists and not empty

**Comment by nathansobo** [comment]
@guziks You've probably tried this a bunch of times, but can you humor me and completely delete the `minimap` package along with the following directories:

* `~/.atom/.apm`
* `~/.atom/.npm`
* `~/.atom/.node-gyp`

I feel like this must be caused by a different issue.

**Comment by Pyraah** [comment]
Same error with 1.0.17.

Clean profil, atom-utils exists and not empty.

![screen error](http://puu.sh/kmPVu.png)

```
Error: Cannot find module 'atom-utils'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\Pyraah\.atom\packages\minimap\lib\minimap-element.coffee:3:40)
  at Object.<anonymous> (C:\Users\Pyraah\.atom\packages\minimap\lib\minimap-element.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Main.activate (C:\Users\Pyraah\.atom\packages\minimap\lib\main.coffee:102:23)
  at Package.module.exports.Package.activateNow (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\package.js:245:19)
  at C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\Pyraah\Downloads\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:371:29
  at exit (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Pyraah\Downloads\Atom\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by kevinsawicki** [comment]
@Pyraah does  `C:\Users\Pyraah\.atom\packages\minimap\node_modules\atom-utils\package.json` exist and is it non-empty?

**Comment by Pyraah** [comment]
@kevinsawicki Yeah this file exist and not empty.
If you want check this file : http://puu.sh/kmR2l.json

**Comment by kevinsawicki** [comment]
@Pyraah @guziks when did you install `minimap` and can you try completely uninstalling that package, then removing the `~/.atom/.apm` directory, and then reinstalling it? Thanks so much for all your help.

**Comment by guziks** [comment]
Uninstalled package, removed `.apm` and `node-gyp`, after reinstall result is the same. By the way it is not just `minimap`, but also 'markdown-themable-pdf' (these ones I know). One detail, I don't have `~/.atom/.npm` at all.

**Comment by Pyraah** [comment]
@kevinsawicki No change for me.
![capture](http://puu.sh/kkBx7.png)

**Comment by daftpanda** [comment]
@kevinsawicki we have to thank you for your efforts and help here :+1: 

well - I can't update anymore (directly from atom itself...):
![image](https://cloud.githubusercontent.com/assets/14540591/10094348/1d0bf59c-635f-11e5-8abf-1304d051f459.png)

and I'm missing the <code>~/.atom/.npm</code> too (since...ever?) like @guziks does...
could this be causing the issues?

**Comment by daftpanda** [comment]
<code>1.0.19</code> and the problem still persists...
I'd like to keep this report alive

**Comment by Evpok** [comment]
Same here. This basically makes atom unusable on Windows.

**Comment by Nonlimit** [comment]
First, the problem solved reinstall to another version. But then there's the problem seemed. Now I sit in Sublime.

**Comment by eliace** [comment]
I have two Atom installations and one of them has the bug. Only difference i've found is Windows 7 and cyrillic symbols in home path.

**Comment by 50Wliu** [comment]
> cyrillic symbols in home path

Interesting...

@daftpanda, are there any spaces or non-Latin symbols in your `%userprofile%` path?

**Comment by daftpanda** [comment]
@50Wliu there are indeed an "ö" and a space in there...
well - my userprofile didn't change since like ever?

**Comment by guziks** [comment]
There is cyrillic user name on my problem system. Also I've checked other computer with latin-only charachters and there is no issue.

**Comment by Evpok** [comment]
Indeed, there is a ï in my user name, but that has never been an issue
before.

**Comment by sebj54** [comment]
Same problem here, I got an é in my HOMEPATH.

**Comment by Astiii** [comment]
Same here, 'á' in user folder name.

**Comment by clemorphy** [comment]
That's it. I have a `é` too in my userprofile path.

**Comment by saviilsy** [comment]
Me too, "ä".

**Comment by 50Wliu** [comment]
Woo, at least it looks like we found the issue :P.

**Comment by daftpanda** [comment]
Seems so :)

**Comment by daftpanda** [comment]
@kevinsawicki so what can we do now? 
I just can't use Atom anymore since the whole issue appeared :-(

**Comment by kevinsawicki** [comment]
@zcbenz do you know of any Electron/node issues regarding `require` and non-ASCII characters in the path?

**Comment by kevinsawicki** [comment]
>  so what can we do now? 

I wonder if this is the issue: https://github.com/nodejs/node/issues/2236 which I believe would be fixed by the Electron upgrade in #8779

**Comment by guziks** [comment]
> I wonder if this is the issue: nodejs/node#2236 which I believe would be fixed by the Electron upgrade in #8779

Wouldn't this mean that every package should fail? I see that some packages fail, also v1.0.11 works without issue.

The only issue I had with non-latin characters affected 'node-gyp' package (all native packages failed to install), but they [resolved](https://github.com/nodejs/node-gyp/commit/39a06bc6092dad3130d349ddb573c666e745535c) it in v2.0.0 and I wonder could it some how be related.

**Comment by kevinsawicki** [comment]
> Wouldn't this mean that every package should fail?

Yeah, that is really interesting. Would it be possible for you to list out which ones fail and which ones pass to see if there is some pattern to it?

>  I see that some packages fail, also v1.0.11 works without issue.

1.0.11 was the last Atom release before Chrome 43 and node 2.3.1 were shipped with Atom which is why I thought it could be that linked issue.

**Comment by Pyraah** [comment]
In my case i can confirm is related to my username (Benoît). With another account named "Testé" i've the same issue, but not with "Pyraah". I hope this can help you...

**Comment by guziks** [comment]
I went through featured packages list and installed them, now I have following packages:

* `atom-grails`
* `atom-jade`
* `color-picker`
* `language-groovy`
* `merge-conflicts`
* `minimap`
* `pigments`
* `sort-lines`
* `travis-ci-status`
* `vim-mode`

These are failed to activate:

* `minimap` (cannot find module `atom-utils`)
* `pigments` (cannot find module `minimatch`)
* `vim-mode` (cannot find module `event-kit`)

**Comment by daftpanda** [comment]
Installed my packages again:

- <code>Remote-FTP</code>
- <code>pigments</code>
- <code>minimap</code>
- <code>linter-less</code>
- <code>linter-csslint</code>
- <code>linter</code>
- <code>keyboard-localization</code>
- <code>file-icons</code>
- <code>fancy-bracket-matcher</code>
- <code>emmet</code>
- <code>css-snippets</code>
- <code>atom-beautify</code>

These failed to load/activate:

- <code>Remote-FTP</code> (cannot find module <code>jslint</code>)
- <code>minimap</code> (cannot find module <code>atom-utils</code>)
- <code>pigments</code> (cannot find module <code>minimatch</code>)
- <code>linter-less</code> (cannot find module <code>atom-linter</code>)
- <code>emmet</code> (cannot find module <code>emmet</code>)

**Comment by daftpanda** [comment]
>Would it be possible for you to list out which ones fail and which ones pass to see if there is some pattern to it?-- <cite>**kevinsawicki**</cite>

**Comment by clemorphy** [comment]
I am unable to use some essential features because of this bug. Can we hope for a fix soon ?

**Comment by steelbrain** [comment]
@clemorphy I think restarting fixes this

**Comment by daftpanda** [comment]
@steelbrain fixes what? the whole issue? well not really :)

**Comment by clemorphy** [comment]
@steelbrain @daftpanda Yes, I have several packages that can't start, probably because of a `é` in my user profile path.
@steelbrain I don't know what is fixed for you when you restart, but a restart doesn't change anything for me concerning this issue.

**Comment by Arcanemagus** [comment]
@steelbrain @clemorphy there are two separate issues that started appearing at the same time, this one dealing with non-ascii characters in the user profile path (which isn't fixed by restarting), and another where certain modules can't be found which is fixed by restarting.

**Comment by LebedevAntony** [comment]
I want to join to @daftpanda question about if we could hope that "whole issue" would be fixed soon...
I tried to build manually last working version 1.0.11 but came across with some troubles with installing required node components and eventually gave up.
If this issue is severe, is it possible to share somewhere (i.e. on github.com/atom/atom/releases) version 1.0.11 without autoupdate?

**Comment by kresimircoko** [comment]
Have the same issue, Windows 10, cyrillic letters in my profile path, looking for a way around without renaming my profile.

**Comment by nathansobo** [comment]
An upgrade of Electron just landed on master. It will be a bit before it's released but we're hoping it resolves the issue.

**Comment by daftpanda** [comment]
installed the <code>v1.1.0-beta1</code> --> the issue persists :(

**Comment by thomasjo** [comment]
@daftpanda The beta release doesn't contain the relevant Electron upgrade. You'll need to build from the master branch.

**Comment by daftpanda** [comment]
oh okay, sorry then...
just assumed it could fix it since @50Wliu suggested 'to update'(https://github.com/atom/atom/issues/9210)

my fault ;)

**Comment by 50Wliu** [comment]
Oops, I thought it did :speak_no_evil: :see_no_evil:.  Sorry!

**Comment by daftpanda** [comment]
Yau -  <code>v. 1.2.0-beta0</code> fixed the whole issue for me.

**System:**
Windows 7 Ultimate 64bit
(non-latin characters in my user profile)

**Comment by joaoportela** [comment]
Updating to ` v1.2.0-beta0` to see if it fixes the issue for me too.

**Comment by 50Wliu** [comment]
:sparkles: :shaved_ice: :fireworks: Thanks for the update @daftpanda and @joaoportela!

**Comment by maxbrunsfeld** [comment]
@daftpanda @joaoportela So glad to hear it! Sorry it took so long.
