### ISSUE TITLE
Atom 1.12.2 fails to build on Slackware Linux 14.2: permissions errors

### ISSUE THREAD

**Issue by fusion809** [atom/atom#13220]
Hi,

On Slackware 14.2 with Node.js 6.9.1 and NPM 3.10.8 I get the build error for Atom 1.12.2:

```bash
Node:   v6.9.1
Npm:    v3.10.8
Installing script dependencies
Installing apm
npm ERR! Linux 4.4.14
npm ERR! argv "/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/bin/node" "/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/.bin/npm" "dedupe"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path /tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/node_modules/npm/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/npm-debug.log
module.js:327
    throw err;
    ^

Error: Cannot find module 'node-gyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at new Install (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/install.js:53:38)
    at Object.module.exports.run (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/apm-cli.js:226:18)
    at Object.<anonymous> (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/cli.js:8:7)
    at Object.<anonymous> (/tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/lib/cli.js:12:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
child_process.js:506
    throw err;
    ^

Error: Command failed: /tmp/SBo/atom-1.12.2/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (/tmp/SBo/atom-1.12.2/script/lib/install-atom-dependencies.js:19:16)
    at Object.<anonymous> (/tmp/SBo/atom-1.12.2/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

using [this](https://raw.githubusercontent.com/fusion809/SlackBuilds/a0ef4fca1b90f9b9f75a35c49b51b6eb5639f611/atom/atom.SlackBuild) SlackBuild. The way I am building this package is via running `sudo ./atom.SlackBuild` where the file `atom.SlackBuild` is the previously linked SlackBuild. I also get the same exact error building Atom 1.12.0 using the SlackBuild provided in the official repositories [here](https://slackbuilds.org/slackbuilds/14.2/development/atom/atom.SlackBuild).

Thanks for your time,
Brenton

**Comment by paulmenzel** [comment]
I can reproduce this problem with [MarIuX64](https://github.molgen.mpg.de/mariux64), a distribution based on Linux From Scratch using the [Bee package manager](http://www.beezinga.org/).

Atom 1.10.2, and 1.12.2 show this problem.

`sudo` is used here, and looking at the permissions, it looks like the ID of the user running `sudo` are used to create the directories.

Installing Atom under the user, everything works fine.

@fusion809, are you using sudo?

**Comment by paulmenzel** [comment]
@fusion809, I just saw, that you alsso use `sudo` in `sudo ./atom.SlackBuild`.

**Comment by fusion809** [comment]
Yeah, should have used `su - c "./atom.SlackBuild"`. Just learnt that so I'm gonna close.

**Comment by paulmenzel** [comment]
The problem seems to be with `script/lib/install-apm.js`.

```
$ nl -ba script/lib/install-apm.js
     1	'use strict'
     2	
     3	const childProcess = require('child_process')
     4	const path = require('path')
     5	
     6	const CONFIG = require('../config')
     7	
     8	module.exports = function () {
     9	  console.log('Installing apm')
    10	  childProcess.execFileSync(
    11	    CONFIG.getNpmBinPath(),
    12	    ['--global-style', '--loglevel=error', 'install'],
    13	    {env: process.env, cwd: CONFIG.apmRootPath}
    14	  )
    15	}
```

**Comment by paulmenzel** [comment]
@fusion809, in my opinion, the installation should work without any problems using `sudo`. It’s a regression in my opinion from 1.9.0. So I’d keep it open, but rephrase the title.

**Comment by fusion809** [comment]
Builds fine for me now though, I even uploaded my tgz to https://github.com/fusion809/SlackBuilds/releases/tag/atom-1.12.2.

**Comment by paulmenzel** [comment]
Do you have more information on how you got it to work with `sudo`?

**Comment by fusion809** [comment]
Nope, as I said I just kept trying it and eventually it worked. Dunno why but it did.

**Comment by buczek** [comment]
We worked around this problem with
  unset SUDO_USER SUDO_UID SUDO_COMMAND SUDO_GID
  start_cmd script/build
in our package build script. Needed other workarounds, because the new atom build system doesn't honor DESTDIR etc.
