### PR TITLE
Use display layers facility of text-buffer; delete all the code they replace

### PR DESCRIPTION
**Pull request by nathansobo**
This PR replaces a bunch of old and twisty code in `TextEditor` with usage of a new facility in the `text-buffer` library introduced in https://github.com/atom/text-buffer/pull/149. You can read that pull request for more information about what replaces all the code we're deleting here.

### CODE REVIEW

**Comment by lee-dohm** [comment]
I'm getting this every time I launch Atom now:

1. Launch Atom

**Atom Version**: 1.9.0-dev-3bbeb9e
**System**: Mac OS X 10.11.4
**Thrown From**: [minimap](https://github.com/atom-minimap/minimap) package, v4.22.1


### Stack Trace

Uncaught TypeError: this.getTextEditor(...).tokenizedLinesForScreenRows is not a function

```
At /Users/Lee/.atom/packages/minimap/lib/mixins/canvas-drawer.js:420

TypeError: this.getTextEditor(...).tokenizedLinesForScreenRows is not a function
    at atom-text-editor-minimap.drawLines (/Users/Lee/.atom/packages/minimap/lib/mixins/canvas-drawer.js:420:40)
    at atom-text-editor-minimap.redrawRangesOnLayer (/Users/Lee/.atom/packages/minimap/lib/mixins/canvas-drawer.js:270:14)
    at atom-text-editor-minimap.updateTokensLayer (/Users/Lee/.atom/packages/minimap/lib/mixins/canvas-drawer.js:136:10)
    at atom-text-editor-minimap.updateCanvas (/Users/Lee/.atom/packages/minimap/lib/mixins/canvas-drawer.js:104:10)
    at atom-text-editor-minimap.update (/Users/Lee/.atom/packages/minimap/lib/minimap-element.js:831:10)
    at /Users/Lee/.atom/packages/minimap/lib/minimap-element.js:732:12
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "source.git-config": [
        "gitconfig"
      ],
      "source.ini": [
        ".flowconfig"
      ],
      "source.ruby": [
        "Brewfile"
      ],
      "text.xml.plist": [
        "plist"
      ]
    },
    "disabledPackages": [
      "spell-check-test",
      "autocomplete-elixir",
      "autocomplete-erlang",
      "pigments",
      "atom-elixir",
      "hyperclick",
      "background-tips"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      ".keep",
      "._*",
      "*.pyc",
      "Thumbs.db"
    ],
    "projectHome": "/Users/Lee/Source",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "minimap": {
    "charHeight": 4,
    "charWidth": 2,
    "plugins": {
      "find-and-replace": true
    },
    "v4Preview": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.0 (inactive)
atom-beautify, v0.29.4 (inactive)
atom-elixir, v0.1.4 (inactive)
atom-pair, v2.0.10 (active)
auto-copyright, v0.5.0 (inactive)
autocomplete-elixir, v1.5.13 (inactive)
autocomplete-emojis, v2.3.0 (active)
autocomplete-erlang, v1.1.1 (inactive)
block-travel, v1.0.4 (active)
broadcast-theme, v1.2.0 (inactive)
bug-report, v0.7.1 (active)
docblockr, v0.7.3 (active)
file-type-icons, v1.0.1 (active)
fortune-background-tips, v1.0.0 (active)
git-diff-details, v1.2.0 (active)
git-time-machine, v1.4.1 (inactive)
hex, v0.6.2 (active)
highlight-selected, v0.11.2 (active)
indentation-indicator, v0.6.0 (active)
language-asciidoc, v0.12.0 (inactive)
language-elixir, v0.12.3 (inactive)
language-erlang, v3.0.0 (inactive)
language-generic-config, v1.0.0 (inactive)
language-haml, v0.24.0 (inactive)
language-jade, v0.7.1 (inactive)
language-mediawiki, v2.0.0 (inactive)
language-nginx, v0.6.1 (inactive)
language-r, v0.4.0 (inactive)
language-swift, v0.4.0 (inactive)
language-todotxt, v0.6.1 (inactive)
language-treetop, v0.1.3 (inactive)
minimap, v4.22.1 (active)
navigator-godef, v1.0.3 (active)
notifications, v0.63.2 (active)
package-sync, v1.0.0 (active)
pigments, v0.26.0 (inactive)
red-wavy-underline, v0.3.0 (active)
set-syntax, v0.3.0 (active)
soft-wrap-indicator, v0.7.0 (active)
sort-lines, v0.14.0 (inactive)
svg-preview, v0.7.4 (active)
tabs-to-spaces, v1.0.2 (active)
toggle-quotes, v1.0.0 (inactive)
word-jumper, v0.3.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.1 (inactive)
one-light-ui, v1.3.1 (active)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.29.2 (active)
autocomplete-snippets, v1.10.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (inactive)
bookmarks, v0.39.0 (active)
bracket-matcher, v0.82.0 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.21.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.0.5 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.30.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.57.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.4.1 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.63.2 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.235.1 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.2.3 (active)
styleguide, v0.45.2 (active)
symbols-view, v0.112.0 (inactive)
tabs, v0.92.2 (active)
timecop, v0.33.1 (active)
tree-view, v0.206.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.51.3 (active)
language-clojure, v0.20.0 (active)
language-coffee-script, v0.46.1 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.1 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.17.0 (active)
language-javascript, v0.110.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.21.1 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.34.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.43.1 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.46.0 (inactive)
language-shellscript, v0.21.1 (inactive)
language-source, v0.9.0 (active)
language-sql, v0.21.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.27.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.5 (inactive)
language-yaml, v0.25.2 (inactive)

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment]
That was never (isn't any longer?) part of the [public API](https://atom.io/docs/api/v1.7.2/TextEditor), so this breaking that isn't really a bug here.

(`linter-flake8` will probably run into similar issues as it digs into non-public parts of that to get data it needs)

**Comment by as-cii** [comment]
> linter-flake8 is running this, probably for similar reasons:
> 
> `textEditor.displayBuffer.tokenizedBuffer.tokenizedLineForRow(lineNumber)`

That code should run smoothly on this branch because we're providing a deprecated version of `DisplayBuffer` [here](https://github.com/atom/atom/blob/ns-switch-to-display-layers/src/text-editor.coffee#L84-L93). Are you observing a different behavior, @Arcanemagus? If so, what's the error you are getting?

> I'm getting this every time I launch Atom now:
> 
> Launch Atom
> Atom Version: 1.9.0-dev-3bbeb9e
> System: Mac OS X 10.11.4
> Thrown From: minimap package, v4.22.1

This seems like a legit failure, because in the process of searching for usages of `tokenizedLineForScreenRow` we didn't pay attention to the _plural_ version of this method, which seems to be used in a couple of packages:

1. minimap
1. jasmine-runner
1. build-systems

Given the small set of packages that use it, however, I don't think we should provide a backward-compatible API in this case. In fact, I think [jasmine-runner](https://github.com/ahuth/jasmine-runner/blob/master/lib/file.coffee#L15) and [build-system](https://github.com/klorenz/atom-build-systems/blob/master/lib/build-output.coffee#L52) can probably just use `tokenizedBuffer.tokenizedLineForRow`.

It seems, however, that the minimap needs to be updated to use the new text decoration facilities and, therefore, I am going to start a PR on that repository to facilitate the update process.

Thoughts? 💭 By the way, thanks everyone for the feedback! 👏

**Comment by Arcanemagus** [comment]
@as-cii Sorry, meant that only as an example of usage of non-public parts of the code, I hadn't actually checked whether it worked on this branch or not :stuck_out_tongue:

**Comment by thedaniel** [comment]
On my machine, with the `language-babel` package activated, opening a JS file and scrolling (for example, `git-repository-async.js`) causes a string of tracebacks, and leaves mouse selection in a broken state (no selection is shown, selection boundaries appear to be not where the mouse was clicked and dragged). I get the following two errors repeated as I scroll:

Tracebacks:
```
TypeError: Cannot read property 'appendChild' of null
    at LinesTileComponent.module.exports.LinesTileComponent.setLineInnerNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:338:26)
    at LinesTileComponent.module.exports.LinesTileComponent.buildLineNode (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:277:12)
    at LinesTileComponent.module.exports.LinesTileComponent.updateLineNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:140:34)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:95:12)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

```
Error: The element cannot be null or undefined.
    at DOMElementPool.module.exports.DOMElementPool.free (/Applications/Atom.app/Contents/Resources/app.asar/src/dom-element-pool.js:80:15)
    at DOMElementPool.module.exports.DOMElementPool.freeElementAndDescendants (/Applications/Atom.app/Contents/Resources/app.asar/src/dom-element-pool.js:63:12)
    at LinesTileComponent.module.exports.LinesTileComponent.removeLineNode (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:108:27)
    at LinesTileComponent.module.exports.LinesTileComponent.removeLineNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:103:14)
    at LinesTileComponent.module.exports.LinesTileComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/lines-tile-component.js:93:14)
    at LinesComponent.module.exports.TiledComponent.updateTileNodes (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:67:19)
    at LinesComponent.module.exports.TiledComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/tiled-component.js:30:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:265:34)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

**Comment by as-cii** [comment]
I filed an issue to jasmine-runner and atom-build-systems, with a possible solution that prevents them from breaking after this pull-request gets merged. Also, @abe33 and I worked on fixing the minimap to play nicely with the old `DisplayBuffer` and the new `DisplayLayer` too.

Since this PR was opened there have been two main changes:

1. `text-buffer` was updated, and it now contains a pretty important update to `atom-patch`;
2. We fixed a problem with reporting wrong close/open scopes in `TokenizedBufferIterator`;

Therefore, I'd recommend re-building the latest version of this branch.

Huge shout-out to everyone who has built this PR locally and has been trying it out! 👏

**Comment by 50Wliu** [comment]
I'm noticing different indent guide behavior on this branch.
On master, indent guides are lazy, eg they are displayed on empty newlines.
On this branch, indent guides are eager, eg they disappear once they hit an empty newline.

This seems to fix #3160.

**Comment by 50Wliu** [comment]
Actually...this new behavior actually seems to be a bug, though perhaps we can adjust it to fix #3160? :grinning: 

image

Similarly...
image

I would expect the indent guides to stay consistent: in the examples shown above, there should be indent guides everywhere where they're missing.

(Sorry for the low contrast)

**Comment by Arcanemagus** [comment]
@50Wliu Are you sure that isn't a theme issue?

image

You don't have invisibles showing in that screenshot, but I'm guessing those "partially guided" lines have some trailing whitespace in there.

**Comment by 50Wliu** [comment]
Nope, I have the Whitespace package on and set to remote all trailing whitespace (I also double-checked before commenting).

Same thing in safe mode.

**Comment by Arcanemagus** [comment]
So after a bit of further testing with @50Wliu we've determined that the indent guide issue may be Windows specific.

In a Ubuntu 16.04 VM with a completely fresh profile, when Indentation Guides are turned on and the following file is opened:

```py
def foo():

    "foo"

        "foo"

        "foo"

            "bar"
```

I get this:
image

While @50Wliu, testing on Windows on a new blank profile sees this:
image

Both of us were on builds based on 9175194.

**Comment by amytruong** [comment]
Some testing that I'm doing. Will continue to edit this as I go. 😁 
- [x] Folds.
- [x] Folding/Unfolding all.
- [x] Folding/Unfolding rows.
- [x] Folding/Unfolding indent levels.
- [x] Free-form folds via Editor: Fold Selection. (basic)
These bugs might be a side effect of this issue: https://github.com/atom/text-document/issues/15. I wasn't sure so wanted to report them to be safe. 
Bug 1
folding
Bug 2
folding2

- [x] Editing before/after a folded row: Found another bug (i think).
**Steps to reproduce:**
1. Fold a selection
2. Click the caret  in the gutter to unfold. 
3. Expected Results: The selection unfolds/expands 
4. Actual Results: The selection does not unfold/expand

caret


- [x] Editing before/after a free-form fold.
- [ ] Duplicating a line with folds (either free-form or row-based ones).
- [ ] Moving up/down a line with folds (either free-form or row-based ones).
- [ ] Editing a line consisting of lots of free-form folds spanning multiple buffer rows, that also cause the screen line to soft-wrap.
- [ ] Expanding/Collapsing folds.
- [ ] Make sure that the right indicator is shown on the gutter for lines with folds.
- [ ] Soft-wrapping.
  - [ ] Editing soft-wrapped "latin" lines.
  - [ ] Editing soft-wrapped "CJK" lines.
  - [ ] Editing soft-wrapped lines with lots of spaces.
  - [ ] Editing soft-wrapped lines with a small window that causes lines to wrap more frequently.
- [ ] [ ] Markers.
- [ ] Core features.
    - [ ] Selections.
    - [ ] Cursors.
- [ ] Packages.
   - [ ] bookmarks.
  -  [ ] find-and-replace.
    - [ ] spell-check.

**Comment by as-cii** [comment]
Thanks for the bug reports everyone! ✨ 

> So after a bit of further testing with @50Wliu we've determined that the indent guide issue may be Windows specific.

That's really weird, as this branch is making changes that are not platform-specific. @50Wliu: could you post a screenshot of the supposedly wrong line's inner HTML? Alternatively I'd be happy to screenshare later today and try to reproduce it together on Windows; I wonder if it could be related to some styling problem (e.g. different font configuration, etc.) rather than to a logic error in `DisplayLayer`.

> Editing before/after a folded row: Found another bug (i think).

Yeah, that's definitely a 🐛. Good catch!

> These bugs might be a side effect of this issue: atom/text-document#15. I wasn't sure so wanted to report them to be safe.

Those two look really suspicious... Taking a 👀 right now!

**Comment by amytruong** [comment]
👍 @as-cii 
Think I may have found something else a little unusual. Posting it just in case. 😁 
expands

**Comment by 50Wliu** [comment]
For extra funsies: I can reproduce the indent guide issue on Ubuntu 16.04 as well.

I found the issue though by following @as-cii's tip about looking at the inner HTML.

It appears that `&#8203` characters (zero-width spaces) are being inserted on empty lines, which are disabling the indent guides.  I **cannot** reproduce this with the code snippet @Arcanemagus shared above, but I can using the code snippet he shared in Slack with me.

**Comment by Arcanemagus** [comment]
Oh crazy, I see the same thing copying back down the Slack snippet!

**Comment by 50Wliu** [comment]
The original screenshots I posted don't have the zero-width spaces though, just some empty `indent-guide` spans.

Example (notice the top-most line):
image

**Comment by 50Wliu** [comment]
Noticed something while trying to move off a long line:
long-line
When clicking another line that's not visible, the screen does not update.  I have to type something or move the cursor using the arrow keys in order for the correct location to show up.

**Comment by as-cii** [comment]
> When clicking another line that's not visible, the screen does not update. I have to type something or move the cursor using the arrow keys in order for the correct location to show up.
> Not sure if this is related to this branch though.

Yeah, seems like master exhibits the same behavior too: I think we explicitly disabled autoscrolling on mouse click because the resulting UX is somewhat worse (e.g. clicking on a visible character which is close to the left margin of the rendered area causes the editor to scroll). Maybe we need finer grained control over autoscroll, but I'd say to address this on a separate pull-request. Thanks for the heads-up, @50Wliu!

**Comment by 50Wliu** [comment]
Here's another regression when trying to select lines (ignore the double-click in the beginning, my mouse is running out of battery):
incorrect-selection

Something similar happens when trying to move the cursor to the first non-whitespace character, though this one is harder to reproduce:
incorrect-cursor-move

**Comment by as-cii** [comment]
@50Wliu: I am pretty sure this got fixed with the latest commit. Can you try reproducing it on 334b4c1?

**Comment by 50Wliu** [comment]
Yup, fixed.  Thanks!

**Comment by amytruong** [comment]
@as-cii :wave: I was testing find & replace (in buffer) and came upon this error message. 
screen shot 2016-05-02 at 2 26 44 pm

Then, I switched to find & replace in project and got an issue with mini map (which seems to be known?) but trying to reproduce it and it isn't happening again (minimap is working fine now) 
screen shot 2016-05-02 at 2 30 12 pm

**Comment by maxbrunsfeld** [comment]
:clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:

**Comment by t9md** [comment]
I'm working on catching-up displayLayer change in my vim-mode-plus package t9md/atom-vim-mode-plus#269.

Noticed two thing.

## Deprecation warning when I pass persistent option like blow.

Reported to atom/text-buffer#154

```coffeescript
editor.markBufferRange editor.getSelectedBufferRange(),
    invalidate: 'never'
    persistent: false
```

## Text wrap point diff when editor.setEditorWidthInChars()

Not sure this is intended of  not.

Noticed by some failing spec(checking behavior in wrapped line).

Maybe related to this commit?

bef7539e3453c049c91c052a3539784eb6fa2694

Here minimum spec to reproduce

```coffeescript
describe "Reproduce wrap diff", ->
  it "wrap line diff with 1.9.0-dev-d06da3f and 1.8.3-beta3", ->
    editor = null
    waitsForPromise ->
      atom.workspace.open(null).then (_editor) ->
        editor = _editor
        editor.setSoftWrapped(true)
        editor.setEditorWidthInChars(10)
        editor.setDefaultCharWidth(1)

        editor.setText """
          1st line of buffer
          2nd line of buffer, Very long line
          3rd line of buffer

          5th line of buffer\n
          """

    runs ->
      {inspect} = require 'util'

      console.log atom.appVersion
      lineTexts = (editor.lineTextForScreenRow(screenRow) for screenRow in [0..4])
      console.log inspect(lineTexts)
      
      # v1.8.0-beta3
      # [ '1st line ',
      #   'of buffer',
      #   '2nd line ',
      #   'of buffer, ',
      #   'Very long ' ]

      # 1.9.0-dev-d06da3f
      # [ '1st line ', 'of buffer', '2nd line ', 'of ', 'buffer, ' ]

```

**Comment by as-cii** [comment]
> Not sure this is intended of not.

Yes, while in the middle of redesigning this part of Atom, we took some time to revisit how lines are soft-wrapped. In the specific case you've mentioned, Atom notices that `of buffer, ` is 11 characters long and will split the line at the beginning of the last word that fitted within 10 characters. In addition, if a line is made up of whitespaces only, Atom will wrap that too, as opposed to keep any number of contiguous whitespace characters within the same line even if they wouldn't fit the requested soft-wrap column.

**Comment by t9md** [comment]
So new wrapping strategy is more intelligent from humans expectation viewpoin.
Great, thanks for explaining that.
