### ISSUE TITLE
Problem when ReadDirectoryChangesW returns CANCELLED

### ISSUE THREAD

**Issue by acjones** [atom/atom#15497]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I open a file that resides on our network file server, Atom crashes after about 20 seconds or so. I think I have some clues as to what is causing this, based on system calls monitored through SysInternals Process Monitor. The crash is always immediately following a call to "NtNotifyChangeDirectoryFile". This call is normally used to allow a process to be notified of changes to a folder, but in some environments this functionality is not supported. In our case, the server is returning "CANCELLED," and presumably the result is not being checked by Atom (or whatever component of Atom is issuing the call).

Note that NtNotifyChangeDirectory is probably not the call in the code, so it's more likely coming from something like ReadDirectoryChangesW. I'm not really that familiar with Atom yet, but my best guess is that this is getting called from Node.js. In particular, node/deps/uv/src/win/fs-event.c.  I can confirm that the filters being set in that file match what is being passed to NtNotifyChangeDirectoryFile right before my crash.

Hope this is helpful!

Function docs for reference.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365465(v=vs.85).aspx

### Steps to Reproduce

1. Open Atom
2. Navigate to a file on NAS that does not support remote monitoring.
3. Keep the page active, and wait for the crash.

**Expected behavior:** The file should remain open with no crash

**Actual behavior:** Atom crashes, offering to close, reopen, or keep open.

**Reproduces how often:** 100% in my environment.

### Versions

Atom 1.19.4 (fresh install)
Atom 1.20.0-beta5 (fresh install)

Windows 8.1

### Additional Information

Our server is a Hitachi HNAS, which is likely to be really hard to replicate. I'm hoping the bug may be self-evident from the code, or perhaps the situation could be reproduced by disabling remote monitoring on a different type of server.

**Comment by rsese** [comment]
Thanks for the report @acjones - to get more information, can you share any crash logs?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

And just to confirm, you've just started with 1.19.4 and 1.20.0-beta5 and weren't running previous versions of Atom?  Wondering if it worked in 1.18.0 or not.

**Comment by rsese** [comment]
There are also a handful of open issues related to network drives e.g. https://github.com/atom/atom/issues/6974.

**Comment by acjones** [comment]
Correct -- I started with 1.19.4 and then tried 1.20.0-beta5, with no previous installs before 1.19.4.

I'll give 1.18.0 a shot and gather some crash logs. I'm assuming the crash logs from 1.20.0-beta5 will work, but let me know if you need them from another version.

**Comment by acjones** [comment]
Crash logs (from 1.20.0-beta5):
https://drive.google.com/open?id=0B_6hK7ibeSg6VVZCa2dqYmVhNnM

I was able to reproduce the same problem in 1.18.0. 

It does sound related to #6974. The difference in my report, from what I can tell, is that I'm not actually doing anything, and the crash is just happening based on background updates.  @Arcanemagus mentions that in the other ticket as well.

Some new info:
1) I noticed I can close the file, and if the Project window is still looking the network share, I still get the same crash.

2) Disabling the "github 0.4.0" package fixes the situation, and I'm no longer seeing crashes.


Looking at the github package, it appears there have been some updates to this file from 0.4.0 to the 0.5.0 tag:
https://github.com/atom/github/blob/master/lib/models/file-system-change-observer.js

In particular:
https://github.com/atom/github/commit/25b767f5f3821afd441dea3002dc93a23cfa8573

I tried sticking 0.5.0 in my packages folder, but it's failing to load (Cannot find module 'atom-babe16-transpiler'). I could probably use a little guidance on getting a working checkout of that package with the updates that will work in 1.20.0-beta5 to test if it fixes the issue.

**Comment by rsese** [comment]
@acjones - we have a new file watcher system that's not enabled by default but is available at `Settings > File System Watcher` if you set it to `Experimental filesystem watching library`.  If you can still reproduce with this setting on the latest versions of Atom, please let us know.

**Comment by egorse** [comment]
@rsese - does that windows specific or linux should be better too? I have really frequent atom crashes when recompiling c\c++ source tree

**Comment by Arcanemagus** [comment]
The new file watcher is cross platform @egorse.

**Comment by egorse** [comment]
@Arcanemagus jeah - experimental fs watching lib works waaaay better - so far no crashes. 
But now seems project find during recompilation might output ENOENT on removed file(s) or stuck (probably on disappearing directory)

**Comment by Arcanemagus** [comment]
> output ENOENT on removed file(s)

That sounds like what it _should_ do? 😕

> or stuck (probably on disappearing directory)

If you think you've spotted an issue in how this is working _please_ file an issue on [atom/watcher](https://github.com/atom/watcher) so we can get this working reliably across all platforms 😉.
